import { Knex } from 'knex';
import { StatusMentoriaEnum } from '../../enum/StatusMentoriaEnum';
import CriptografarSenha from '../../utils/CriptografarSenha';

export async function seed(knex: Knex): Promise<void> {
  await knex('usuarios').insert([
    {
      id: 1,
      nome: 'Afonso',
      sobrenome: 'Chaves',
      data_nascimento: '2001/01/12',
      email: 'primeiro@seed.com.br',
      celular: 13981873109,
      apresentacao: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      senha: CriptografarSenha('123'),
      genero: 1,
      mentor: true,
      mentorado: false,
    },
    {
      id: 2,
      nome: 'Gabryelle',
      sobrenome: 'dos Santos',
      data_nascimento: '2001/01/12',
      email: 'segundo@seed.com.br',
      celular: 13981232139,
      apresentacao: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make.",
      senha: CriptografarSenha('123'),
      genero: 2,
      mentor: true,
      mentorado: true,
    },
    {
      id: 3,
      nome: 'João',
      sobrenome: 'da Silva',
      data_nascimento: '2001/01/12',
      email: 'terceiro@seed.com.br',
      celular: 33333333333,
      apresentacao: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      senha: CriptografarSenha('123'),
      genero: 3,
      mentor: true,
      mentorado: false,
    },
    {
      id: 4,
      nome: 'Marlon',
      sobrenome: 'Roberto',
      data_nascimento: '2001/01/12',
      email: 'quarto@seed.com.br',
      celular: 44444444444,
      apresentacao: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard.",
      senha: CriptografarSenha('123'),
      genero: 3,
      mentor: true,
      mentorado: false,
    },
    {
      id: 5,
      nome: 'Rodrigo',
      sobrenome: 'Mercúrio',
      data_nascimento: '2001/01/12',
      email: 'quinto@seed.com.br',
      celular: 55555555555,
      senha: CriptografarSenha('1232'),
      genero: 3,
      mentor: true,
      mentorado: false,
    },
  ]);

  await knex('tags').insert([
    {
      id: 1,
      nome: 'Programação',
    },
    {
      id: 2,
      nome: 'Mobile',
    },
    {
      id: 3,
      nome: 'UI/UX',
    },
    {
      id: 4,
      nome: 'Web',
    },
  ]);

  await knex('usuarios_tags').insert([
    { id_mentorado: 1, id_tag: 1 },
    { id_mentorado: 1, id_tag: 2 },
    { id_mentorado: 1, id_tag: 3 },
    { id_mentorado: 1, id_tag: 4 },

    { id_mentorado: 2, id_tag: 1 },
    { id_mentorado: 2, id_tag: 3 },
    { id_mentorado: 2, id_tag: 4 },

    { id_mentor: 2, id_tag: 1 },
    { id_mentor: 2, id_tag: 2 },
    { id_mentor: 2, id_tag: 3 },

    { id_mentor: 3, id_tag: 1 },
    { id_mentor: 3, id_tag: 2 },
    { id_mentor: 3, id_tag: 3 },

    { id_mentor: 4, id_tag: 1 },
    { id_mentor: 4, id_tag: 2 },

    { id_mentor: 5, id_tag: 1 },
  ]);

  await knex('notificacoes').insert([
    {
      id: 1,
      status: 1,
      mensagem: 'Mensagem 1',
      id_mentorado: 1,
    },
    {
      id: 2,
      status: 2,
      mensagem: 'Mensagem 2',
      id_mentorado: 2,
    },
    {
      id: 3,
      status: 3,
      mensagem: 'Mensagem 3',
      id_mentor: 2,
    },
    {
      id: 4,
      status: 1,
      mensagem: 'Mensagem 4',
      id_mentor: 3,
    },
  ]);

  await knex('mentorias').insert([
    {
      id: 1,
      id_mentorado: 2,
      id_mentor: 1,
      data_inicio: '2022/01/12',
      status: StatusMentoriaEnum.EM_ANDAMENTO,
      avaliacao_mentor: 1,
      avaliacao_mentorado: 5,
    },
    {
      id: 2,
      id_mentorado: 2,
      id_mentor: 1,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 2,
      avaliacao_mentorado: 5,
    },
    {
      id: 3,
      id_mentorado: 2,
      id_mentor: 3,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.AGUARDANDO,
      avaliacao_mentor: 3,
      avaliacao_mentorado: 5,
    },
    {
      id: 4,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 4,
      avaliacao_mentorado: 5,
    },
    {
      id: 5,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 5,
      avaliacao_mentorado: 5,
    },
    {
      id: 6,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 1.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 7,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 2.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 8,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 3.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 9,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 3.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 10,
      id_mentorado: 1,
      id_mentor: 4,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 2.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 11,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 1.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 12,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 4.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 13,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 4.5,
      avaliacao_mentorado: 5,
    },
  ]);

  await knex('mensagens').insert([
    {
      mensagem: 'Mensagem teste 1',
      data_envio: '2022-04-23 10:03:52',
      id_mentor: 5,
      id_mentorado: 1,
      tipo_enviado: 'mentorado',
    },
    {
      mensagem: 'Mensagem teste 2',
      data_envio: '2022-04-23 11:03:52',
      id_mentor: 5,
      id_mentorado: 1,
      tipo_enviado: 'mentor',
    },
    {
      mensagem: 'Mensagem teste 3',
      data_envio: '2022-04-23 12:03:52',
      id_mentor: 5,
      id_mentorado: 1,
      tipo_enviado: 'mentor',
    },
    {
      mensagem: 'Mensagem teste 4',
      data_envio: '2022-04-23 13:03:52',
      id_mentor: 5,
      id_mentorado: 1,
      tipo_enviado: 'mentorado',
    },
    {
      mensagem: 'Mensagem teste 5',
      data_envio: '2022-04-23 14:03:52',
      id_mentor: 5,
      id_mentorado: 1,
      tipo_enviado: 'mentorado',
    },
  ]);
}
