import { Knex } from 'knex';
import { StatusMentoriaEnum } from '../../enum/StatusMentoriaEnum';
import CriptografarSenha from '../../utils/CriptografarSenha';

export async function seed(knex: Knex): Promise<void> {
  await knex('usuarios').insert([
    {
      id: 1,
      nome: 'Mentorado 1',
      sobrenome: 'Mentorado 1',
      data_nascimento: '2001/01/12',
      email: 'primerio@seed.com.br',
      celular: 11111111111,
      senha: CriptografarSenha('primerio@seed.com.br'),
      genero: 1,
      mentor: false,
      mentorado: true,
    },
    {
      id: 2,
      nome: 'Mentor e Mentorado',
      sobrenome: 'Mentor e Mentorado',
      data_nascimento: '2001/01/12',
      email: 'segundo@seed.com.br',
      celular: 22222222222,
      senha: CriptografarSenha('segundo@seed.com.br'),
      genero: 2,
      mentor: true,
      mentorado: true,
    },
    {
      id: 3,
      nome: 'Mentor 1',
      sobrenome: 'Mentor',
      data_nascimento: '2001/01/12',
      email: 'terceiro@seed.com.br',
      celular: 33333333333,
      senha: CriptografarSenha('terceiro@seed.com.br'),
      genero: 3,
      mentor: true,
      mentorado: false,
    },
    {
      id: 4,
      nome: 'Mentor 2',
      sobrenome: 'Mentor',
      data_nascimento: '2001/01/12',
      email: 'quarto@seed.com.br',
      celular: 44444444444,
      senha: CriptografarSenha('quarto@seed.com.br'),
      genero: 3,
      mentor: true,
      mentorado: false,
    },
    {
      id: 5,
      nome: 'Mentor 3',
      sobrenome: 'Mentor',
      data_nascimento: '2001/01/12',
      email: 'quinto@seed.com.br',
      celular: 55555555555,
      senha: CriptografarSenha('quinto@seed.com.br'),
      genero: 3,
      mentor: true,
      mentorado: false,
    },
  ]);

  await knex('cursos').insert([
    {
      id: 1,
      nome: 'Curso 1',
      instituicao: 'Instituição 1',
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      tipo_curso: 'Tecnólogo',
      id_mentor: 2,
    },
    {
      id: 2,
      nome: 'Curso 2',
      instituicao: 'Instituição 2',
      data_inicio: '2022/02/12',
      data_fim: '2022/02/20',
      tipo_curso: 'Técnico',
      id_mentor: 3,
    },
  ]);

  await knex('tags').insert([
    {
      id: 1,
      nome: 'Tag 1',
    },
    {
      id: 2,
      nome: 'Tag 2',
    },
    {
      id: 3,
      nome: 'Tag 3',
    },
    {
      id: 4,
      nome: 'Tag 4',
    },
  ]);

  await knex('usuarios_tags').insert([
    { id_mentorado: 1, id_tag: 1 },
    { id_mentorado: 1, id_tag: 2 },
    { id_mentorado: 1, id_tag: 3 },

    { id_mentorado: 2, id_tag: 1 },
    { id_mentorado: 2, id_tag: 2 },
    { id_mentorado: 2, id_tag: 3 },

    { id_mentor: 2, id_tag: 1 },
    { id_mentor: 2, id_tag: 2 },
    { id_mentor: 2, id_tag: 3 },

    { id_mentor: 3, id_tag: 1 },
    { id_mentor: 3, id_tag: 2 },
    { id_mentor: 3, id_tag: 3 },

    { id_mentor: 4, id_tag: 1 },
    { id_mentor: 4, id_tag: 2 },

    { id_mentor: 5, id_tag: 1 },
  ]);

  await knex('notificacoes').insert([
    {
      id: 1,
      status: 1,
      mensagem: 'Mensagem 1',
      id_mentorado: 1,
    },
    {
      id: 2,
      status: 2,
      mensagem: 'Mensagem 2',
      id_mentorado: 2,
    },
    {
      id: 3,
      status: 3,
      mensagem: 'Mensagem 3',
      id_mentor: 2,
    },
    {
      id: 4,
      status: 1,
      mensagem: 'Mensagem 4',
      id_mentor: 3,
    },
  ]);

  await knex('mentorias').insert([
    {
      id: 1,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 1,
      avaliacao_mentorado: 5,
    },
    {
      id: 2,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 2,
      avaliacao_mentorado: 5,
    },
    {
      id: 3,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 3,
      avaliacao_mentorado: 5,
    },
    {
      id: 4,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 4,
      avaliacao_mentorado: 5,
    },
    {
      id: 5,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 5,
      avaliacao_mentorado: 5,
    },
    {
      id: 6,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 1.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 7,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 2.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 8,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 3.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 9,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 3.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 10,
      id_mentorado: 1,
      id_mentor: 4,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 2.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 11,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 1.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 12,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 4.5,
      avaliacao_mentorado: 5,
    },
    {
      id: 13,
      id_mentorado: 1,
      id_mentor: 5,
      data_inicio: '2022/01/12',
      data_fim: '2022/01/20',
      status: StatusMentoriaEnum.FINALIZADA,
      avaliacao_mentor: 4.5,
      avaliacao_mentorado: 5,
    },
  ]);
}
