USE learnbetter;

CREATE TABLE IF NOT EXISTS ADMINISTRADORES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(30) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  email VARCHAR(60) NOT NULL
);
CREATE TABLE IF NOT EXISTS TAGS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS MENTORADOS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(30) NOT NULL,
  sobrenome VARCHAR(50) NOT NULL,
  data_nascimento DATE NOT NULL,
  email VARCHAR(60) NOT NULL,
  celular VARCHAR(11) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  genero CHAR(1) NOT NULL,
  data_criacao DATE NOT NULL DEFAULT (CURRENT_DATE),
  data_ultima_atualizacao DATE
);
CREATE TABLE IF NOT EXISTS MENTORADOS_TAGS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_mentorado INT NOT NULL,
  id_tag INT NOT NULL,
  FOREIGN KEY (id_mentorado) REFERENCES MENTORADOS (id),
  FOREIGN KEY (id_tag) REFERENCES TAGS (id)
);
CREATE TABLE IF NOT EXISTS MENTORES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(30) NOT NULL,
  sobrenome VARCHAR(50) NOT NULL,
  data_nascimento DATE NOT NULL,
  email VARCHAR(60) NOT NULL,
  celular VARCHAR(11) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  genero CHAR(1) NOT NULL,
  data_criacao DATE NOT NULL DEFAULT (CURRENT_DATE),
  data_ultima_atualizacao DATE,
  apresentacao TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS MENTORES_TAGS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_mentor INT NOT NULL,
  id_tag INT NOT NULL,
  FOREIGN KEY (id_mentor) REFERENCES MENTORES (id),
  FOREIGN KEY (id_tag) REFERENCES TAGS (id)
);
CREATE TABLE IF NOT EXISTS CURSOS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_mentor INT NOT NULL,
  nome VARCHAR(30) NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  certificado VARCHAR(50) NOT NULL,
  instituicao VARCHAR(40) NOT NULL,
  tipo_curso VARCHAR(40) NOT NULL,
  FOREIGN KEY (id_mentor) REFERENCES MENTORES (id)
);
CREATE TABLE IF NOT EXISTS MENTORIAS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_mentor INT NOT NULL,
  id_mentorado INT NOT NULL,
  avaliacao_mentorado INT,
  avaliacao_mentor INT,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  -- 0- RECUSADA 1- AGUARDANDO 2- EM ANDAMENTO 3- FINALIZADO
  FOREIGN KEY (id_mentorado) REFERENCES MENTORADOS (id),
  FOREIGN KEY (id_mentor) REFERENCES MENTORES (id)
);
CREATE TABLE IF NOT EXISTS CHAT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_mentor INT NOT NULL,
  id_mentorado INT NOT NULL,
  mensagem TEXT NOT NULL,
  data_envio DATE NOT NULL DEFAULT (CURRENT_DATE),
  FOREIGN KEY (id_mentorado) REFERENCES MENTORADOS (id),
  FOREIGN KEY (id_mentor) REFERENCES MENTORES (id)
);